auto: true
server: true
markdown: kramdown
server_port: 3000
pygments: false
lsi: false
permalink: /episode/:title/
#paginate: 10
name: THC fyi  
description: Marijuana Variety Show
url: http://twitter.com/thc_fyi
rss: http://thcfyi.github.io./feed.xml
logo: http://thcfyi.github.io/img/Unknown-1.png
